### ISSUE TITLE
Latest PyPi release is broken

### ISSUE THREAD

**Issue by j-zimmermann** [GuignardLab/LineageTree#38]
Dear developers,

Thanks for the great code and sharing it openly!
Unfortunately, there is the bug in the latest release 1.5.0.
In this line, `warnings` is used but it has not been imported:
https://github.com/GuignardLab/LineageTree/blob/52b093267eb159f9344b9da0486ef6a4a118de03/src/LineageTree/lineageTreeManager.py#L8
In turn, a `NameError` is raised.
Importing `warnings` fixes this bug.

Best,
Julius

**Comment by leoguignard** [comment]
Thanks a lot for nice comments. And thanks for letting us know about the bug.
Can you double check that @BadPrograms please?

**Comment by leoguignard** [comment]
Note that if you install LineageTree with:
```shell
pip install "LineageTree[treeedit]"
```
You should not have the problem anymore (though it's not a fix).

Alternatively you can run:
```shell
pip install edist
```
In the environment where lineageTree is installed which should avoid the issue (still not a fix but a hack).

Best,
Léo

**Comment by leoguignard** [comment]
The problem should now be fixed with version `1.5.1`.

Thanks for the feedback, I'm closing the issue.
